"""Fix Order, session_id Int->UUID

Revision ID: 3835b00ba3f7
Revises: 856de8941207
Create Date: 2026-08-08 11:56:55.177084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3835b00ba3f7'
down_revision: Union[str, Sequence[str], None] = '856de8941207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
