"""fix

Revision ID: 8ae4541191b1
Revises: 36fd24124eb8
Create Date: 2026-08-26 16:33:46.933443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ae4541191b1'
down_revision: Union[str, Sequence[str], None] = '36fd24124eb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tool_call_records', 'result_tool')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool_call_records', sa.Column('result_tool', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
