"""add table waypoints

Revision ID: 0ac447ef3507
Revises: 9d01d113ad40
Create Date: 2026-08-10 13:58:01.937659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ac447ef3507'
down_revision: Union[str, Sequence[str], None] = '9d01d113ad40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waypoints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('waypoint_town', sa.String(length=250), nullable=True),
    sa.Column('waypoint_town_id', sa.Integer(), nullable=True),
    sa.Column('waypoint_district', sa.String(length=250), nullable=True),
    sa.Column('waypoint_district_id', sa.Integer(), nullable=True),
    sa.Column('waypoint_street', sa.String(length=250), nullable=True),
    sa.Column('waypoint_street_id', sa.Integer(), nullable=True),
    sa.Column('waypoint_house', sa.String(length=50), nullable=True),
    sa.Column('waypoint_house_id', sa.Integer(), nullable=True),
    sa.Column('waypoint_landmark', sa.String(length=250), nullable=True),
    sa.Column('waypoint_landmark_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['waypoint_district_id'], ['districts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['waypoint_house_id'], ['houses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['waypoint_landmark_id'], ['landmarks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['waypoint_street_id'], ['streets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['waypoint_town_id'], ['towns.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waypoints_waypoint_street_id'), 'waypoints', ['waypoint_street_id'], unique=False)
    op.add_column('orders', sa.Column('pickup_town', sa.String(length=250), nullable=True))
    op.add_column('orders', sa.Column('pickup_town_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('pickup_district', sa.String(length=250), nullable=True))
    op.add_column('orders', sa.Column('pickup_district_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('pickup_house', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('pickup_house_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('pickup_landmark', sa.String(length=250), nullable=True))
    op.add_column('orders', sa.Column('pickup_landmark_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('destination_town', sa.String(length=250), nullable=True))
    op.add_column('orders', sa.Column('destination_town_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('destination_district', sa.String(length=250), nullable=True))
    op.add_column('orders', sa.Column('destination_district_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('destination_house', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('destination_house_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('destination_landmark', sa.String(length=250), nullable=True))
    op.add_column('orders', sa.Column('destination_landmark_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('driver_id', sa.Uuid(), nullable=True))
    op.add_column('orders', sa.Column('driver_assigned_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('trip_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('trip_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('orders', 'state',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('draft', 'confirmed', 'searghing', 'assigned', 'in_progress', 'completed', 'cancelled', name='order_state', native_enum=False),
               existing_nullable=False)
    op.drop_index(op.f('ix_orders_waypoint_street_id'), table_name='orders')
    op.drop_constraint(op.f('orders_waypoint_street_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'landmarks', ['pickup_landmark_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'orders', 'districts', ['destination_district_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'orders', 'houses', ['destination_house_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'orders', 'towns', ['destination_town_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'orders', 'landmarks', ['destination_landmark_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'orders', 'districts', ['pickup_district_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'orders', 'towns', ['pickup_town_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'orders', 'houses', ['pickup_house_id'], ['id'], ondelete='SET NULL')
    op.drop_column('orders', 'waypoint_street')
    op.drop_column('orders', 'waypoint_street_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('waypoint_street_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('waypoint_street', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_waypoint_street_id_fkey'), 'orders', 'streets', ['waypoint_street_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_orders_waypoint_street_id'), 'orders', ['waypoint_street_id'], unique=False)
    op.alter_column('orders', 'state',
               existing_type=sa.Enum('draft', 'confirmed', 'searghing', 'assigned', 'in_progress', 'completed', 'cancelled', name='order_state', native_enum=False),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    op.drop_column('orders', 'trip_completed_at')
    op.drop_column('orders', 'trip_started_at')
    op.drop_column('orders', 'driver_assigned_at')
    op.drop_column('orders', 'driver_id')
    op.drop_column('orders', 'destination_landmark_id')
    op.drop_column('orders', 'destination_landmark')
    op.drop_column('orders', 'destination_house_id')
    op.drop_column('orders', 'destination_house')
    op.drop_column('orders', 'destination_district_id')
    op.drop_column('orders', 'destination_district')
    op.drop_column('orders', 'destination_town_id')
    op.drop_column('orders', 'destination_town')
    op.drop_column('orders', 'pickup_landmark_id')
    op.drop_column('orders', 'pickup_landmark')
    op.drop_column('orders', 'pickup_house_id')
    op.drop_column('orders', 'pickup_house')
    op.drop_column('orders', 'pickup_district_id')
    op.drop_column('orders', 'pickup_district')
    op.drop_column('orders', 'pickup_town_id')
    op.drop_column('orders', 'pickup_town')
    op.drop_index(op.f('ix_waypoints_waypoint_street_id'), table_name='waypoints')
    op.drop_table('waypoints')
    # ### end Alembic commands ###
