"""Order, waypoints fix =all, delete-orphan

Revision ID: 35fc908bab90
Revises: c5c0e0c33ff9
Create Date: 2026-08-20 17:09:37.001123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35fc908bab90'
down_revision: Union[str, Sequence[str], None] = 'c5c0e0c33ff9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
