"""add waypoint fields to orders

Revision ID: 9d01d113ad40
Revises: 3835b00ba3f7
Create Date: 2026-08-08 16:33:46.587569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d01d113ad40'
down_revision: Union[str, Sequence[str], None] = '3835b00ba3f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('waypoint_street', sa.String(length=250), nullable=True))
    op.add_column('orders', sa.Column('waypoint_street_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_orders_waypoint_street_id'), 'orders', ['waypoint_street_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'streets', ['waypoint_street_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_waypoint_street_id'), table_name='orders')
    op.drop_column('orders', 'waypoint_street_id')
    op.drop_column('orders', 'waypoint_street')
    # ### end Alembic commands ###
