"""add relationship Message+ToolCallRecord fix

Revision ID: c45756fa365b
Revises: ed88b9b0885e
Create Date: 2026-08-27 20:09:03.670381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c45756fa365b'
down_revision: Union[str, Sequence[str], None] = 'ed88b9b0885e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
