"""fix tool_call_record

Revision ID: 1755e90b5385
Revises: c45756fa365b
Create Date: 2026-08-27 20:21:27.837167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1755e90b5385'
down_revision: Union[str, Sequence[str], None] = 'c45756fa365b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool_call_records', sa.Column('thought_signature', sa.Text(), nullable=True))
    op.add_column('tool_call_records', sa.Column('reasoning_content', sa.Text(), nullable=True))
    op.add_column('tool_call_records', sa.Column('response_id', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tool_call_records', 'response_id')
    op.drop_column('tool_call_records', 'reasoning_content')
    op.drop_column('tool_call_records', 'thought_signature')
    # ### end Alembic commands ###
