"""add relationship Message+ToolCallRecord

Revision ID: ed88b9b0885e
Revises: 8ae4541191b1
Create Date: 2026-08-27 20:04:34.177642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed88b9b0885e'
down_revision: Union[str, Sequence[str], None] = '8ae4541191b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
