"""init alembic

Revision ID: 856de8941207
Revises: 
Create Date: 2026-08-07 07:17:34.932144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '856de8941207'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('console', 'telegram', 'phone', name='call_channel', native_enum=False), nullable=False),
    sa.Column('handled_by', sa.Enum('bot', 'operator', name='handled_by', native_enum=False), nullable=False),
    sa.Column('external_call_id', sa.String(length=64), nullable=True),
    sa.Column('caller_phone', sa.String(length=100), nullable=True),
    sa.Column('caller_name', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unknown_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_call_id')
    )
    op.create_table('towns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_price', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_towns_id'), 'towns', ['id'], unique=False)
    op.create_index(op.f('ix_towns_name'), 'towns', ['name'], unique=False)
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('town_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price_override', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['town_id'], ['towns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_districts_id'), 'districts', ['id'], unique=False)
    op.create_index(op.f('ix_districts_name'), 'districts', ['name'], unique=False)
    op.create_index(op.f('ix_districts_town_id'), 'districts', ['town_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('call_session_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', 'tool', name='message_role', native_enum=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tool_call_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_session_id'], ['call_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_session_id', 'sequence_number', name='uq_messages_session_sequence')
    )
    op.create_index(op.f('ix_messages_call_session_id'), 'messages', ['call_session_id'], unique=False)
    op.create_table('streets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price_override', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streets_district_id'), 'streets', ['district_id'], unique=False)
    op.create_index(op.f('ix_streets_id'), 'streets', ['id'], unique=False)
    op.create_index(op.f('ix_streets_name'), 'streets', ['name'], unique=False)
    op.create_table('tool_call_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('tool_call_id', sa.String(length=100), nullable=False),
    sa.Column('function_name', sa.String(length=100), nullable=False),
    sa.Column('arguments', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_call_records_message_id'), 'tool_call_records', ['message_id'], unique=False)
    op.create_table('houses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['street_id'], ['streets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('street_id', 'number', name='uq_house_street_number')
    )
    op.create_index(op.f('ix_houses_number'), 'houses', ['number'], unique=False)
    op.create_index(op.f('ix_houses_street_id'), 'houses', ['street_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('call_session_id', sa.Uuid(), nullable=False),
    sa.Column('pickup_street', sa.String(length=250), nullable=True),
    sa.Column('pickup_street_id', sa.Integer(), nullable=True),
    sa.Column('destination_street', sa.String(length=250), nullable=True),
    sa.Column('destination_street_id', sa.Integer(), nullable=True),
    sa.Column('passenger_name', sa.String(length=100), nullable=True),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('state', sa.Enum('draft', 'confirmed', 'completed', 'cancelled', name='order_state', native_enum=False), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_session_id'], ['call_sessions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['destination_street_id'], ['streets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pickup_street_id'], ['streets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_orders_call_session_id'), 'orders', ['call_session_id'], unique=False)
    op.create_index(op.f('ix_orders_destination_street_id'), 'orders', ['destination_street_id'], unique=False)
    op.create_index(op.f('ix_orders_pickup_street_id'), 'orders', ['pickup_street_id'], unique=False)
    op.create_index(op.f('ix_orders_state'), 'orders', ['state'], unique=False)
    op.create_table('street_synonyms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['street_id'], ['streets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('street_id', 'name', name='uq_street_synonym_name')
    )
    op.create_index(op.f('ix_street_synonyms_id'), 'street_synonyms', ['id'], unique=False)
    op.create_index(op.f('ix_street_synonyms_name'), 'street_synonyms', ['name'], unique=False)
    op.create_index(op.f('ix_street_synonyms_street_id'), 'street_synonyms', ['street_id'], unique=False)
    op.create_table('landmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street_id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['street_id'], ['streets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_landmarks_house_id'), 'landmarks', ['house_id'], unique=False)
    op.create_index(op.f('ix_landmarks_name'), 'landmarks', ['name'], unique=False)
    op.create_index(op.f('ix_landmarks_street_id'), 'landmarks', ['street_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_landmarks_street_id'), table_name='landmarks')
    op.drop_index(op.f('ix_landmarks_name'), table_name='landmarks')
    op.drop_index(op.f('ix_landmarks_house_id'), table_name='landmarks')
    op.drop_table('landmarks')
    op.drop_index(op.f('ix_street_synonyms_street_id'), table_name='street_synonyms')
    op.drop_index(op.f('ix_street_synonyms_name'), table_name='street_synonyms')
    op.drop_index(op.f('ix_street_synonyms_id'), table_name='street_synonyms')
    op.drop_table('street_synonyms')
    op.drop_index(op.f('ix_orders_state'), table_name='orders')
    op.drop_index(op.f('ix_orders_pickup_street_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_destination_street_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_call_session_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_houses_street_id'), table_name='houses')
    op.drop_index(op.f('ix_houses_number'), table_name='houses')
    op.drop_table('houses')
    op.drop_index(op.f('ix_tool_call_records_message_id'), table_name='tool_call_records')
    op.drop_table('tool_call_records')
    op.drop_index(op.f('ix_streets_name'), table_name='streets')
    op.drop_index(op.f('ix_streets_id'), table_name='streets')
    op.drop_index(op.f('ix_streets_district_id'), table_name='streets')
    op.drop_table('streets')
    op.drop_index(op.f('ix_messages_call_session_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_districts_town_id'), table_name='districts')
    op.drop_index(op.f('ix_districts_name'), table_name='districts')
    op.drop_index(op.f('ix_districts_id'), table_name='districts')
    op.drop_table('districts')
    op.drop_index(op.f('ix_towns_name'), table_name='towns')
    op.drop_index(op.f('ix_towns_id'), table_name='towns')
    op.drop_table('towns')
    op.drop_table('call_sessions')
    # ### end Alembic commands ###
