"""add last_message_sequence to call_session

Revision ID: 70edfb6af74e
Revises: 1755e90b5385
Create Date: 2026-08-30 11:45:17.254355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70edfb6af74e'
down_revision: Union[str, Sequence[str], None] = '1755e90b5385'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_sessions', sa.Column('last_message_sequence', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call_sessions', 'last_message_sequence')
    # ### end Alembic commands ###
