"""add price in House

Revision ID: c5c0e0c33ff9
Revises: 0ac447ef3507
Create Date: 2026-08-15 12:31:16.189036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5c0e0c33ff9'
down_revision: Union[str, Sequence[str], None] = '0ac447ef3507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('price_override', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('houses', 'price_override')
    # ### end Alembic commands ###
