"""add order_number

Revision ID: 8f39bebd9d8a
Revises: 35fc908bab90
Create Date: 2026-08-23 14:38:36.586560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f39bebd9d8a'
down_revision: Union[str, Sequence[str], None] = '35fc908bab90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_number', sa.Integer(), nullable=False))
    op.create_unique_constraint('uq_orders_call_session_order_number', 'orders', ['call_session_id', 'order_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_orders_call_session_order_number', 'orders', type_='unique')
    op.drop_column('orders', 'order_number')
    # ### end Alembic commands ###
